config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :authors, only: %i[show]

  resources :posts do
    collection do
      get :export
    end

    member do
      post :publish
    end
  end

  root 'posts#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
# frozen_string_literal: true

class Author < ApplicationRecord
  has_many :posts, dependent: :nullify
  has_many :published_posts, -> { published }, class_name: 'Post', dependent: :nullify, inverse_of: :author
  has_many :recent_posts, -> { recents }, class_name: 'Post', dependent: :nullify, inverse_of: :author

  has_one :profile, inverse_of: :author, dependent: :destroy

  accepts_nested_attributes_for :profile, allow_destroy: true

  validates :email, format: { with: /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\z/i, message: 'Invalid email' }
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :author, inverse_of: :posts, autosave: true

  has_one :author_profile, through: :author, source: :profile

  has_many :post_tags, inverse_of: :post, dependent: :destroy
  has_many :tags, through: :post_tags

  validates :title, allow_blank: false, presence: true

  scope :published, -> { where.not(published_at: nil) }
  scope :recents, -> { where('created_at > ?', 3.months.ago) }
end

app/models/post_tag.rb
# frozen_string_literal: true

class PostTag < ApplicationRecord
  belongs_to :post, inverse_of: :post_tags, optional: false
  belongs_to :tag,  inverse_of: :post_tags, optional: false
end

app/models/profile.rb
# frozen_string_literal: true

class Profile < ApplicationRecord
  belongs_to :author, inverse_of: :profile, touch: true
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :post_tags, inverse_of: :tag, dependent: :destroy
  has_many :posts, through: :post_tags

  validates :name, allow_blank: false, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
# frozen_string_literal: true

class AuthorsController < ApplicationController
  before_action :load_author, only: %i[show]

  # GET /authors/1
  def show; end

  private

  def load_author
    @author = Author.find(params.require(:id))
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :load_post, only: %i[show edit publish update destroy]

  # GET /posts
  def index
    @posts = Posts::ListService.call
  end

  # GET /posts/export
  def export
    Posts::ExportService.call(listeners: [self])
  end

  def export_success(csv_data)
    respond_to do |format|
      format.csv do
        response.headers['Content-Type'] = 'text/csv'
        response.headers['Content-Disposition'] = 'attachment; filename=export.csv'

        render inline: csv_data
      end
    end
  end

  # GET /posts/1
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts/1/publish
  def publish
    Posts::PublishService.call(post: @post, listeners: [self])
  end

  def publish_failure(post, message)
    notice = message == :already_published ? 'Post already published.' : 'Post was not successfully published.'
    respond_to do |format|
      format.html { redirect_to post, notice: notice }
    end
  end

  def publish_success(post)
    respond_to do |format|
      format.html { redirect_to post, notice: 'Post was successfully published.' }
    end
  end

  # POST /posts
  def create
    Posts::CreateService.call(attrs: post_params, listeners: [self])
  end

  def create_failure(post)
    @post = post
    respond_to do |format|
      format.html { render :new }
    end
  end

  def create_success(post)
    respond_to do |format|
      format.html { redirect_to post, notice: 'Post was successfully created.' }
    end
  end

  # PATCH/PUT /posts/1
  def update
    Posts::UpdateService.call(post: @post, attrs: post_params, listeners: [self])
  end

  def update_failure(post)
    respond_to do |format|
      format.html { render :edit }
    end
  end

  def update_success(post)
    respond_to do |format|
      format.html { redirect_to post, notice: 'Post was successfully updated.' }
    end
  end

  # DELETE /posts/1
  def destroy
    Posts::DestroyService.call(post: @post)
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
    end
  end

  private

  def load_post
    @post = Posts::LoadService.call(params[:id])
  end

  def post_params
    params.fetch(:post) { {} }.permit!
  end
end

app/views/authors/_author.html.erb
<div>
  <div class="item"><b>Name</b>: <%= author.name %></div>
  <div class="item"><b>Age</b>: <%= author.age %></div>
  <div class="item"><b>E-mail</b>: <%= author.email %></div>

  <% if author.profile %>
    <hr/>
    <div class="item"><b>More information</b>: <%= author.profile.description %></div>
  <% end %>
</div>

app/views/authors/show.html.erb
<h1>Author</h1>

<%= render 'author', author: @author %>

<br/>

<%= link_to 'Home', root_path, class: 'button button-outline' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsHexagonalApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/milligram/1.4.1/milligram.css">

    <style>
      body { background: #f4f4f4; min-height: 100vh; }
      .button_to { display: inline-block; }
      .container { background: #fff; min-height: 100vh; padding-top: 25px; }
      .field label { display: inline-block; margin-right: 10px; padding-left: 5px; }
    </style>
  </head>
  <body>
    <div class="container">
      <% if flash[:notice] %>
        <div class="notice"><%= flash[:notice] %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |form| %>
  <% if @post.errors.any? %>
    <div><%= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:" %></div>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="field">
    <div class="author">Author:</div>
    <%= form.collection_select :author_id, Author.order(:name), :id, :name %>
  </div>

  <div class="field">
    <div class="title">Title:</div>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <div class="description">Description:</div>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <div class="category">Category:</div>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <div class="position">Position:</div>
    <%= form.text_field :position %>
  </div>

  <div class="field">
    <div class="tags">Tags:</div>
    <%= form.collection_check_boxes :tag_ids, Tag.order(:name), :id, :name %>
  </div>

  <br/>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div>
  <div class="item"><b>Author</b>: <%= link_to post.author %></div>
  <div class="item"><b>Title</b>: <%= post.title %></div>
  <div class="item"><b>Description</b>: <%= post.description %></div>
  <div class="item"><b>Created at</b>: <%= post.created_at %></div>
  <div class="item"><b>Category</b>: <%= post.category %></div>
  <div class="item"><b>Position</b>: <%= post.position %></div>
  <div class="item"><b>Tags</b>: <%= post.tags_list %></div>
  <div class="item"><b>Published at</b>: <%= post.published_at %></div>
</div>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render 'form' %>

<hr/>

<%= link_to 'Show', post_path(@post), class: 'button button-outline' %>
<%= link_to 'Back', posts_path, class: 'button button-clear' %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<ul>
<% @posts.each do |post| %>
  <li>
    <span class="title"><%= post.title %></span> by <%= link_to post.author %><br/>
    <em><%= post.published_at ? '[published]' : '[NOT published]' %></em><br/>
    <%= link_to 'Show', post, class: 'button button-outline' %>
    <%= link_to 'Edit', edit_post_path(post), class: 'button button-outline' %>
    <%= button_to 'Publish', publish_post_path(post), method: :post, class: 'button button-outline' %>
    <%= button_to 'Destroy', post, data: { confirm: 'Are you sure?' }, method: :delete, class: 'button button-outline' %>
  </li>
<% end %>
</ul>

<hr/>

<%= link_to 'New post', new_post_path, class: 'button button-outline' %>
<%= link_to 'Export titles', export_posts_path(format: :csv), class: 'button button-outline' %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<hr/>

<%= link_to 'Back', posts_path, class: 'button button-clear' %>

app/views/posts/show.html.erb
<h1>Post</h1>

<%= render 'post', post: @post %>

<hr/>

<%= link_to 'Edit', edit_post_path(@post), class: 'button button-outline' %>
<%= button_to 'Publish', publish_post_path(@post), method: :post, class: 'button button-outline' %>
<%= link_to 'Back', posts_path, class: 'button button-clear' %>